version:  '3'
services:
  team5-tick_to_min:
      build: .
      restart: unless-stopped
      container_name: team5-tick_to_min
      env_file:
        - .env
      networks:
        - team5

networks:
  team5:
    external: True